_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVSS,VMOVSS,",
    offsets = "-16,-24,",
    addresses = "0x163e,0x1648,",
    stride_status = "Success",
    stride = 24,
    memory_status = "Success",
    accessed_memory = 8,
    accessed_memory_nooverlap = 8,
    accessed_memory_overlap = 0,
    span = 12,
    head = 0,
    unroll_factor = 2,
  },
  {
    group_size = 1,
    pattern = "L",
    opcodes = "VMOVSS,",
    offsets = "4,",
    addresses = "0x1630,",
    stride_status = "Success",
    stride = 24,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
}
