_group = {
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x4025a4,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x402584,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x4025bd,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 9,
    pattern = "SLLLLSLLL",
    opcodes = "VMOVSS,MOV,VMULSS,MOV,VMULSS,VMOVSS,MOV,VMULSS,CMP,",
    offsets = "0,16,0,24,0,40,32,40,8,",
    addresses = "0x402516,0x402528,0x402535,0x40254d,0x402575,0x40257a,0x402597,0x4025b7,0x4025e3,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 52,
    accessed_memory_nooverlap = 40,
    accessed_memory_overlap = 12,
    span = 44,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x40253a,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x4025d9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 5,
    pattern = "LLLLL",
    opcodes = "VMULSS,VMULSS,VMOVSS,VMULSS,VMULSS,",
    offsets = "64907,64870,64851,64796,64743,",
    addresses = "0x40252d,0x402552,0x402565,0x40259c,0x4025d1,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 20,
    accessed_memory_nooverlap = 20,
    accessed_memory_overlap = 0,
    span = 168,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x40255a,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
}
