_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x401433,0x40143a,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x40144e,0x401455,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x401418,0x40141f,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
}
