_group = {
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x401269,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 6,
    pattern = "LLLLLL",
    opcodes = "MOV,MOV,MOV,MOV,MOV,MOV,",
    offsets = "0,8,16,24,32,40,",
    addresses = "0x401234,0x40124d,0x401265,0x40127f,0x401297,0x4012b1,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 48,
    accessed_memory_nooverlap = 48,
    accessed_memory_overlap = 0,
    span = 48,
    head = 0,
    unroll_factor = 6,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x401283,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x401237,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x40129b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x401251,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "VMOVSS,VMULSS,VMULSS,VMULSS,",
    offsets = "3552,3511,3461,3411,",
    addresses = "0x40121c,0x401245,0x401277,0x4012a9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 145,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x4012b5,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 5,
    pattern = "SLSLL",
    opcodes = "VMOVSS,VMULSS,VMOVSS,VMULSS,VMULSS,",
    offsets = "4,4,4,4,4,",
    addresses = "0x40120d,0x401224,0x40122a,0x40125f,0x401291,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 20,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 16,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
}
