_group = {
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x4015b3,0x4015ba,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x401598,0x40159f,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
  {
    group_size = 2,
    pattern = "LL",
    opcodes = "VMOVUPS,VMOVUPS,",
    offsets = "0,64,",
    addresses = "0x4015ce,0x4015d5,",
    stride_status = "Success",
    stride = 128,
    memory_status = "Success",
    accessed_memory = 128,
    accessed_memory_nooverlap = 128,
    accessed_memory_overlap = 0,
    span = 128,
    head = 128,
    unroll_factor = 2,
  },
}
