_group = {
  {
    group_size = 5,
    pattern = "SSLLL",
    opcodes = "MOV,VMOVSS,VMULSS,VMULSS,VMULSS,",
    offsets = "12,12,12,12,12,",
    addresses = "0x1b7d,0x1b94,0x1ba7,0x1bd9,0x1c0b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 20,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 16,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1bdf,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1bf9,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 6,
    pattern = "LLLLLL",
    opcodes = "MOV,MOV,MOV,MOV,MOV,MOV,",
    offsets = "0,8,16,24,32,40,",
    addresses = "0x1ba3,0x1bbb,0x1bd5,0x1bed,0x1c07,0x1c1f,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 48,
    accessed_memory_nooverlap = 48,
    accessed_memory_overlap = 0,
    span = 48,
    head = 0,
    unroll_factor = 6,
  },
  {
    group_size = 4,
    pattern = "LLLL",
    opcodes = "VMOVSS,VMULSS,VMULSS,VMULSS,",
    offsets = "1424,1369,1319,1269,",
    addresses = "0x1b8c,0x1bbf,0x1bf1,0x1c23,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 16,
    accessed_memory_nooverlap = 16,
    accessed_memory_overlap = 0,
    span = 159,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1bad,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1bc7,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1c11,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
  {
    group_size = 1,
    pattern = "S",
    opcodes = "VMOVSS,",
    offsets = "0,",
    addresses = "0x1c2b,",
    stride_status = "Not mono block loop",
    stride = 0,
    memory_status = "Success",
    accessed_memory = 4,
    accessed_memory_nooverlap = 4,
    accessed_memory_overlap = 0,
    span = 4,
    head = 0,
    unroll_factor = 1,
  },
}
